# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hbv_sim <- function(P, E, Tavg, tt, cfmax, sfcf, cfr, cwh, fc, lp, beta, initialise_sm) {
    .Call('_hydromad_hbv_sim', PACKAGE = 'hydromad', P, E, Tavg, tt, cfmax, sfcf, cfr, cwh, fc, lp, beta, initialise_sm)
}

hbvrouting_sim <- function(U, perc, uzl, k0, k1, k2, wi, n_maxbas, initial_lz) {
    .Call('_hydromad_hbvrouting_sim', PACKAGE = 'hydromad', U, perc, uzl, k0, k1, k2, wi, n_maxbas, initial_lz)
}

hbv_pet <- function(dates, Tavg, PET, Tmean, cet) {
    .Call('_hydromad_hbv_pet', PACKAGE = 'hydromad', dates, Tavg, PET, Tmean, cet)
}

simhyd_sim <- function(P, E, INSC, COEFF, SQ, SMSC, SUB, CRAK, K, GWt0, SMSt0) {
    .Call('_hydromad_simhyd_sim', PACKAGE = 'hydromad', P, E, INSC, COEFF, SQ, SMSC, SUB, CRAK, K, GWt0, SMSt0)
}

