on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: roxygenise

jobs:
  document:
    if: startsWith(github.event.comment.body, '/document')
    name: document
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        
      - uses: r-lib/actions/pr-fetch@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: r-lib/actions/setup-r@master
        
      - name: Install dependencies
        run: |
          remotes::install_cran("rcmdcheck")
          remotes::install_cran("Rcpp")
          remotes::install_cran("coda")
          remotes::install_github("TillF/ppso")
          remotes::install_github("roxygen2")
          remotes::install_url("http://download.r-forge.r-project.org/src/contrib/dream_0.4-2.tar.gz")
          remotes::install_deps(dependencies = TRUE)

      - name: Document
        run: Rscript -e 'roxygen2::roxygenise()'

      - name: Rcpp attributes
        run: Rscript -e 'Rcpp::compileAttributes()'

      - name: commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add man/\* NAMESPACE R/RcppExports.R src/RcppExports.cpp
          git commit -m 'Document'
      - uses: r-lib/actions/pr-push@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
